/**
 * alfa
 * beta
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 48928310+averge@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoinIncludeFilterItems } from './coinIncludeFilterItems';


export interface CoinFilter1 { 
    offset?: number;
    limit?: number;
    skip?: number;
    order?: string | Array<string> | null;
    where?: { [key: string]: object; };
    fields?: object | Set<string> | null;
    include?: Array<CoinIncludeFilterItems | string>;
}

