/**
 * alfa
 * beta
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 48928310+averge@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Partial<Coin>, schemaOptions: { partial: true })
 */
export interface CoinPartial { 
    id?: string;
    nombre?: string;
    sufijo?: string;
    precio?: number;
    descripcion?: string;
    link?: string;
}

