/**
 * alfa
 * beta
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 48928310+averge@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: ExchangeWithRelations, schemaOptions: { includeRelations: true })
 */
export interface ExchangeWithRelations { 
    id?: string;
    nombre: string;
    link?: string;
    script?: string;
    coinId?: string;
}

